version: "2"
services:
  kserver:
    image: edtasixm11/k18:kserver
    container_name: kserver.edt.org
    networks:
      - mynet
  sshd:
    image: edtasixm11/k18:sshd
    container_name: sshd.edt.org
    networks:
      - mynet        
networks:
  mynet:
